# Generated by Django 6.0a1 on 2026-04-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='genero')),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viuvo(a)'), ('outro', 'Outro')], max_length=15, verbose_name='estado civil')),
                ('naturalidade', models.CharField(blank=True, max_length=100, verbose_name='naturalidade')),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=100, verbose_name='nacionalidade')),
                ('nome_mae', models.CharField(max_length=255, verbose_name='nome da mae')),
                ('nome_pai', models.CharField(blank=True, max_length=255, verbose_name='nome do pai')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/fotos/', verbose_name='foto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('telefone_alternativo', models.CharField(blank=True, max_length=20, verbose_name='telefone alternativo')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=255, verbose_name='logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='numero')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhao'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PR', 'Parana'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'Sao Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('consentimento_lgpd', models.BooleanField(default=False, verbose_name='consentimento LGPD')),
                ('data_consentimento', models.DateTimeField(blank=True, null=True, verbose_name='data do consentimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('comprovante_residencia', 'Comprovante de Residencia'), ('certidao_nascimento', 'Certidao de Nascimento'), ('certidao_casamento', 'Certidao de Casamento'), ('cnh', 'CNH Anterior'), ('foto_3x4', 'Foto 3x4'), ('outro', 'Outro')], max_length=30, verbose_name='tipo')),
                ('arquivo', models.FileField(upload_to='alunos/documentos/', verbose_name='arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descricao')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='alunos.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['tipo'],
            },
        ),
    ]
