# Generated by Django 6.0a1 on 2026-04-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('psicotecnico', 'Psicotecnico'), ('medico', 'Exame Medico'), ('teorico_detran', 'Exame Teorico - DETRAN'), ('pratico_detran', 'Exame Pratico - DETRAN')], max_length=20, verbose_name='tipo')),
                ('resultado', models.CharField(choices=[('agendado', 'Agendado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('ausente', 'Ausente'), ('cancelado', 'Cancelado')], default='agendado', max_length=15, verbose_name='resultado')),
                ('data_agendamento', models.DateField(verbose_name='data de agendamento')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='local')),
                ('data_resultado', models.DateField(blank=True, null=True, verbose_name='data do resultado')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'exame',
                'verbose_name_plural': 'exames',
                'ordering': ['-data_agendamento'],
            },
        ),
    ]
