# Generated by Django 6.0a1 on 2026-04-06 12:45

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(unique=True, verbose_name='data')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='saldo inicial')),
                ('fechado', models.BooleanField(default=False, verbose_name='fechado')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='data de fechamento')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'caixa diario',
                'verbose_name_plural': 'caixas diarios',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor total')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='desconto')),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor de entrada')),
                ('numero_parcelas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='numero de parcelas')),
                ('dia_vencimento', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='dia de vencimento')),
                ('data_contrato', models.DateField(default=datetime.date.today, verbose_name='data do contrato')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-data_contrato'],
            },
        ),
        migrations.CreateModel(
            name='LogFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('contrato', 'Contrato'), ('parcela', 'Parcela'), ('caixa', 'Caixa Diario'), ('movimento', 'Movimento de Caixa')], max_length=20, verbose_name='modelo')),
                ('objeto_id', models.PositiveIntegerField(verbose_name='ID do objeto')),
                ('campo', models.CharField(max_length=100, verbose_name='campo alterado')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='valor anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='valor novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='data da alteracao')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_financeiros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log financeiro',
                'verbose_name_plural': 'logs financeiros',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='numero')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('data_vencimento', models.DateField(verbose_name='data de vencimento')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=15, verbose_name='status')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data do pagamento')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, verbose_name='forma de pagamento')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='financeiro.contrato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'parcela',
                'verbose_name_plural': 'parcelas',
                'ordering': ['contrato', 'numero'],
                'unique_together': {('contrato', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=10, verbose_name='tipo')),
                ('categoria', models.CharField(choices=[('mensalidade', 'Mensalidade'), ('parcela', 'Parcela de Contrato'), ('taxa_exame', 'Taxa de Exame'), ('material', 'Material Didatico'), ('despesa_operacional', 'Despesa Operacional'), ('salario', 'Salario'), ('combustivel', 'Combustivel'), ('manutencao', 'Manutencao'), ('outros', 'Outros')], max_length=25, verbose_name='categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.caixadiario')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.parcela')),
            ],
            options={
                'verbose_name': 'movimento de caixa',
                'verbose_name_plural': 'movimentos de caixa',
                'ordering': ['-caixa__data', '-criado_em'],
            },
        ),
    ]
