# Generated by Django 6.0a1 on 2026-04-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrutores', '0001_initial'),
        ('matriculas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('teorica', 'Teorica'), ('pratica_simulador', 'Pratica - Simulador'), ('pratica_via_publica', 'Pratica - Via Publica'), ('direcao_defensiva', 'Direcao Defensiva'), ('primeiros_socorros', 'Primeiros Socorros')], max_length=25, verbose_name='tipo')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('falta_aluno', 'Falta do Aluno'), ('falta_instrutor', 'Falta do Instrutor'), ('cancelada', 'Cancelada'), ('remarcada', 'Remarcada')], default='agendada', max_length=20, verbose_name='status')),
                ('data', models.DateField(verbose_name='data')),
                ('hora_inicio', models.TimeField(verbose_name='hora de inicio')),
                ('hora_fim', models.TimeField(verbose_name='hora de fim')),
                ('km_inicial', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM inicial')),
                ('km_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM final')),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, help_text='Nota de 1 a 10', null=True, verbose_name='avaliacao')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='instrutores.instrutor')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='matriculas.matricula')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='instrutores.veiculo')),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
