# Generated by Django 6.0a1 on 2026-04-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_credencial', models.CharField(max_length=50, unique=True, verbose_name='numero da credencial')),
                ('data_emissao_credencial', models.DateField(verbose_name='data de emissao')),
                ('data_vencimento_credencial', models.DateField(verbose_name='data de vencimento')),
                ('especialidades', models.CharField(choices=[('A', 'Categoria A (Motos)'), ('B', 'Categoria B (Carros)'), ('AB', 'Categorias A e B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E')], max_length=5, verbose_name='especialidades')),
                ('cor_agenda', models.CharField(choices=[('#f97316', 'Laranja'), ('#3b82f6', 'Azul'), ('#10b981', 'Verde'), ('#8b5cf6', 'Roxo'), ('#ef4444', 'Vermelho'), ('#f59e0b', 'Amarelo'), ('#ec4899', 'Rosa'), ('#06b6d4', 'Ciano')], default='#f97316', max_length=7, verbose_name='cor na agenda')),
                ('numero_cnh', models.CharField(max_length=20, verbose_name='numero da CNH')),
                ('categoria_cnh', models.CharField(max_length=5, verbose_name='categoria da CNH')),
                ('validade_cnh', models.DateField(verbose_name='validade da CNH')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'instrutor',
                'verbose_name_plural': 'instrutores',
                'ordering': ['usuario__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='marca')),
                ('ano', models.PositiveIntegerField(verbose_name='ano')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('caminhao', 'Caminhao'), ('onibus', 'Onibus')], max_length=20, verbose_name='tipo')),
                ('categoria', models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E')], max_length=2, verbose_name='categoria')),
                ('cor', models.CharField(max_length=50, verbose_name='cor')),
                ('renavam', models.CharField(max_length=20, unique=True, verbose_name='RENAVAM')),
                ('chassi', models.CharField(max_length=50, unique=True, verbose_name='chassi')),
                ('data_licenciamento', models.DateField(verbose_name='data do licenciamento')),
                ('km_atual', models.PositiveIntegerField(default=0, verbose_name='KM atual')),
                ('em_manutencao', models.BooleanField(default=False, verbose_name='em manutencao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'veiculo',
                'verbose_name_plural': 'veiculos',
                'ordering': ['placa'],
            },
        ),
    ]
