# Generated by Django 6.0a1 on 2026-04-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('cobranca', 'Cobranca de Parcela'), ('lembrete_aula', 'Lembrete de Aula'), ('lembrete_exame', 'Lembrete de Exame'), ('parabens_aprovacao', 'Parabens por Aprovacao'), ('aniversario', 'Aniversario'), ('boas_vindas', 'Boas Vindas'), ('outro', 'Outro')], max_length=25, unique=True, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('conteudo', models.TextField(help_text='Variaveis disponiveis: {nome}, {valor}, {data}, {hora}, {instrutor}, {tipo}, {local}', verbose_name='conteudo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'template de mensagem',
                'verbose_name_plural': 'templates de mensagens',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='LogNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('mensagem_enviada', models.TextField(verbose_name='mensagem enviada')),
                ('telefone_destino', models.CharField(max_length=20, verbose_name='telefone destino')),
                ('url_whatsapp', models.URLField(max_length=500, verbose_name='URL WhatsApp')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('simulado', 'Simulado'), ('erro', 'Erro')], max_length=15, verbose_name='status')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='alunos.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='notificacoes.templatemensagem')),
            ],
            options={
                'verbose_name': 'log de notificacao',
                'verbose_name_plural': 'logs de notificacoes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
