# Generated by Django 6.0a1 on 2026-04-06 12:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_processo', models.CharField(blank=True, max_length=15, unique=True, verbose_name='numero do processo')),
                ('categoria', models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('AB', 'Categorias A e B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E'), ('ACC', 'ACC')], max_length=5, verbose_name='categoria')),
                ('modalidade', models.CharField(choices=[('CFCA', 'CFCA - Motos'), ('CFCB', 'CFCB - Carros')], max_length=5, verbose_name='modalidade')),
                ('tipo_processo', models.CharField(choices=[('primeira_habilitacao', 'Primeira Habilitacao'), ('adicao_categoria', 'Adicao de Categoria'), ('renovacao', 'Renovacao'), ('mudanca_categoria', 'Mudanca de Categoria'), ('reabilitacao', 'Reabilitacao')], max_length=25, verbose_name='tipo de processo')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('aguardando_exame', 'Aguardando Exame'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada'), ('bloqueada', 'Bloqueada')], default='aberta', max_length=20, verbose_name='status')),
                ('data_matricula', models.DateField(default=datetime.date.today, verbose_name='data da matricula')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='data de conclusao')),
                ('aulas_teoricas_realizadas', models.PositiveIntegerField(default=0, verbose_name='aulas teoricas realizadas')),
                ('aulas_praticas_realizadas', models.PositiveIntegerField(default=0, verbose_name='aulas praticas realizadas')),
                ('bloqueada_revisao', models.BooleanField(default=False, verbose_name='bloqueada para revisao')),
                ('motivo_bloqueio', models.TextField(blank=True, verbose_name='motivo do bloqueio')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='alunos.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'matricula',
                'verbose_name_plural': 'matriculas',
                'ordering': ['-data_matricula'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status_anterior', models.CharField(max_length=20, verbose_name='status anterior')),
                ('status_novo', models.CharField(max_length=20, verbose_name='status novo')),
                ('justificativa', models.TextField(verbose_name='justificativa')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='data da alteracao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'historico de status',
                'verbose_name_plural': 'historicos de status',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
